### ISSUE TITLE
Maybe allow dash to be used in labels

### ISSUE THREAD

**Issue by ahto** [josemrb/ecto_ltree#15]
Hi,

We tried to use UUID7 converted to string as the label for ltree but we had to convert `-` to `_`.

I was wondering why the regex for label doesnt allow `-`.

The [manual for postgres](https://www.postgresql.org/docs/current/ltree.html#LTREE-DEFINITIONS) mention "the characters `A-Za-z0-9_-` are allowed" but the [label regexp](https://github.com/josemrb/ecto_ltree/blob/develop/lib/ecto_ltree/label_tree.ex#L46) is different

**Comment by josemrb** [comment]
Hi @ahto 

Because it is not backwards compatible, Postgres added support for the hyphen symbol in version 16.
