### ISSUE TITLE
Need documentation

### ISSUE THREAD

**Issue by laibulle** [josemrb/ecto_ltree#3]
Hello, 

I didn't find a way to query ltree with the library, so for now I use fragments:

```elixir
from u in "users",
          where: fragment(" path ~ ?", ^value)
```

do you provide any function to do that ?

Best regards

**Comment by josemrb** [comment]
Hi,

> do you provide any function to do that ?

Nope, because Ecto does not support custom operators, fragments are the way to achieve what you need.

Although maybe this could be implemented with macros but I have not tried it yet.

**Comment by crbelaus** [comment]
I would recommend against implementing macros to avoid using fragments.

Fragments are the most flexible way to invoke custom Postgres operators. Creating a set of macros would require maintaining at least one macro per operator, which are [plenty][1].

In the event of a new operator added or removed to a certain PostgreSQL version, the library would have to document the compatibilty of the macros and keep it updated with the upstream changes.

[1]: https://www.postgresql.org/docs/current/ltree.html#id-1.11.7.30.5
