### ISSUE TITLE
Evaluating this library

### ISSUE THREAD

**Issue by SimunKaracic** [josemrb/ecto_ltree#4]
Hello, 
I'm evaluating using this library instead of rolling my own. 

Is there a reason why this is on version 0.20.1? Is appears development has stopped, and I'm just wondering what You think is missing to get this to version 1.0.0.

**Comment by josemrb** [comment]
Hi @SimunKaracic ,

I extracted this library from another project and at the time I had the idea to maybe add a few modules to support the implementation of the materialized path pattern.

Today I think the library is feature complete and if there is anything to do before releasing v1.0 it would be to review the documentation.
